config/routes.rb
Rails.application.routes.draw do

  resources :posts do
    resources :comments
  end

  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]

  root "posts#index"

  get '/about', to: 'pages#about'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { minimum: 5}
  validates_presence_of :body

  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, uniqueness: true
  validates_presence_of :email, :username
  validates :password, presence: { on: :create }, length: { minimum: 6 }, confirmation: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:name, :body))

    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts = Post.all.order('created_at DESC')
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)

		if @post.save
			respond_to do |f| 
				f.html { redirect_to root_path }
				f.js
			end
		else
			render 'new'
		end
	end

	def show
		@post = Post.find(params[:id])
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])

		if @post.update(params[:post].permit(:title, :body))
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy

		redirect_to root_path
	end

	private
		def post_params
			params.require(:post).permit(:title, :body)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
    session[:user_id] = nil
  end

  def create
    @user = User.find_by(email: params[:email]).try(:authenticate, params[:password])
    if @user
      session[:user_id] = @user.id
      redirect_to root_path, alert: "Welcome! Time to blahg."
    else
      flash.now[:error] = "We could not log yu in. Plz check your email & password and try again."
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "You have successfully logged out of the blahg."
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash.now[:error] = "We could not register you. Please include all information, and try again."
      render 'new', status: 422
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    session[:user_id] != nil
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
  <div class="comment_content">
    <p class="comment_name"><strong><%= comment.name %></strong></p>
    <p class="comment_body"><%= comment.body %></p>
    <p class="comment_time"><%= time_ago_in_words(comment.created_at) %> Ago</p>
  </div>
  <p><%= link_to 'Delete', [comment.post, comment],
                  method: :delete,
                  class: "button",
                  data: { confirm: 'Are you sure?'} %>
  </p>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= favicon_link_tag 'favicon.png' %>
    <%= csrf_meta_tags %>

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Ubuntu" />

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
  </head>

  <body>

  	<!--- Namespacing: we can nest classes like my #sidebar and #logo below (but think classes) so as to only add certain styling to a certain nested combination -->
  	<div id="sidebar">
  		<div id="logo">
  			<%= link_to root_path do %>
  				<%= image_tag "dddragon.png" %>
  			<% end %>
  		</div>

  		<ul>
  			<li class="category">Website</li>
  			<li><%= link_to "Blog", root_path %></li>
  			<li><%= link_to "About", about_path %></li>
  		</ul>
  		<ul>
  			<li class="category">Social</li>
  			<li><a href="https://6r36.wordpress.com/2012/01/05/happy-new-ynternet-2/">Hong Kong</a></li>
  			<li><a href="https://6r36.wordpress.com/2012/03/20/loose-ends/">Morocco</a></li>
  			<li><a href="https://6r36.wordpress.com/2011/03/08/marocco-part-2/">Morocco 2</a></li>
  			<li><a href="https://6r36.wordpress.com/2011/03/12/morocco-final-part/">Morocco 3</a></li><br>
  			<li><a href="/posts/new">New Post</a></li>
  		</ul>

      <% if !logged_in? %>
  		  <p class="sign_in"><%= link_to "Admin Login", new_session_path %></p>
      <% end %>
  	</div>

    <div id="main_content">
      <div id="header">
        <% if current_page?(root_path) %>
          <p>All Posts</p>
        <% elsif current_page?(about_path) %>
          <p>About</p>
        <% else %>
          <%= link_to "Back to All Posts", root_path %>
        <% end %>

        <div class="buttons">
        <% if current_user %>
            <p>Hi <%= current_user.username %></p>
            <button class="new-post-button"><%= link_to "New Post", new_post_path, remote: true %></button>
            <%= link_to "Logout", session_path(current_user), method: :delete %>
 <!---           <button class="button"<%= link_to "Logout", session_path(current_user), method: :delete %></button> -->
        <% else %>
            <button class="register-button"><%= link_to "Register", new_user_path %></button>
        <% end %>
        </div>

      </div>

      <% flash.each do |name, message| %>
        <%= content_tag(:div, message, class: "alert") %>
      <% end %>

      <%= yield %>
    </div>

  </body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
  <div id="profile_image">

  </div>

  <div id="content">
    <h1>i'm greghubdub</h1>
    <p>Polsterchild of waviness</p>
    <p>Welcome to my blog</p>
    <p>Cloud bread humblebrag put a bird on it sartorial gochujang. Letterpress brooklyn waistcoat semiotics vinyl. Tofu street art gluten-free, cliche squid poutine hexagon disrupt narwhal normcore pork belly live-edge. Waistcoat pug listicle, retro brooklyn celiac cray pinterest plaid +1 PBR&B craft beer cardigan. Pour-over locavore intelligentsia street art. Kale chips church-key pop-up stumptown shoreditch yuccie master cleanse paleo gentrify hexagon migas woke art party kinfolk. Flexitarian knausgaard migas raw denim letterpress, flannel helvetica tbh forage. Mixtape tote bag butcher air plant, cray drinking vinegar deep v ramps humblebrag street art whatever asymmetrical. Kitsch bitters street art before they sold out. +1 hell of kogi XOXO hammock hella, single-origin coffee meditation kickstarter cray messenger bag blog swag. Meh cred narwhal mlkshk roof party wayfarers, heirloom ugh banjo williamsburg coloring book chicharrones helvetica. Raw denim marfa swag, migas before they sold out williamsburg tilde YOLO gentrify tote bag.</p>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_for @post, remote: true do |f| %>
    <% if @post.errors.any? %>
      <div id="errors">
        <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving</h2>
        <ul>
          <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :body %>
      <%= f.text_area :body %>
    </p>

    <p>
      <%= f.submit %>
    </p>
  <% end %>

app/views/posts/_post.html.erb
<!-- <div class="post-wrapper">
	<h2 class="title"><%= link_to post.title, post %></h2>
	<p class="date"><%= post.created_at.strftime("%B %d, %Y") %></p>
</div> -->

app/views/posts/create.js.erb
$('.container').prepend("<%= j render (@post) %>");
$('.new_post').hide();
$('.new-post-button').show();

app/views/posts/edit.html.erb
<div id="page_wrapper">
  <h1>Edit Post</h1>

  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
	<div class="post-wrapper">
		<h2 class="title"><%= link_to post.title, post %></h2>
		<p class="date"><%= post.created_at.strftime("%B %d, %Y") %></p>
	</div>
<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
	<h1>New Post</h1>

	<%= render 'form' %>
</div>

app/views/posts/new.js.erb
$(".new-post-button").after('<%= j render ('form') %>');
$(".new-post-button").hide();

app/views/posts/show.html.erb
<div id="post_content">
  <h1 class="title">
	 <%= @post.title %>
  </h1>

  <p class="date">
	 Submitted <%= time_ago_in_words(@post.created_at) %> Ago
   | <%= link_to 'Edit', edit_post_path(@post) %>
   | <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %>
  </p>

  <p class="body">
	 <%= @post.body %>
  </p>

  <div id="comments">
    <h2><%= @post.comments.count %> Comments</h2>
    <%= render @post.comments %>

    <h3>Add a comment:</h3>
    <%= render "comments/form" %>
  </div>
</div>

app/views/users/new.html.erb
<h1>Register</h1>

<%= form_with model: @user, local: true, class: "registration-form" do |form| %>
  <%= form.text_field :email, placeholder: "Email" %>
  <%= form.text_field :username, placeholder: "Username" %>
  <%= form.password_field :password, placeholder: "Password" %>
  <%= form.password_field :password_confirmation, placeholder: "Confirm Password" %>
  <%= form.submit "Git ready to blahg" %>
<% end %>